openapi: 3.0.0
info:
  description: "API for sm'Art application"
  version: "1.0.0"
  title: "Smart"
tags:
- name: "base"
  description: "This is great !"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
servers:
  - url: http://localhost:3000/
    description: Optional server description, e.g. Main (production) server

components:
  schemas:
    BasicArtwork:
      properties:
        name: 
          type: string
        artists:
          type: string
        date: 
          type: integer
        link:
          type: string
    MusicArtwork:
      allOf:
      - $ref: '#/components/schemas/BasicArtwork'
      - properties:
          category: 
            type: string
            enum:
             - music
          album:
            type: string
          description:
            type: string
          singer:
            type: string
          composer:
            type: string
          author:
            type: string
        
paths:
  /artworks/{artworkId}:
    get:
      tags: 
      - "artwork"
      summary: "get artwork by Id"
      operationId: "getArworkById"
      parameters:
      - name: "artworkId"
        in: "path"
        description: "ID of artwork to return"
        required: true 
        schema:
          type: string
      responses:
        200:
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MusicArtwork"
externalDocs:
  description: "template for everything here"
  url: "https://editor.swagger.io/"