openapi: 3.0.0
info:
  description: "API for sm'Art application"
  version: "1.0.0"
  title: "Smart"
tags:
- name: "base"
  description: "This is great !"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
servers:
  - url: http://localhost:3000/
    description: Optional server description, e.g. Main (production) server

components:
  schemas:
    Category:
      type: string
      enum:
      - music
      - movie
      - freeText
      - painting
      - photography
    BasicArtwork:
      properties:
        name: 
          type: string
        artists:
          type: string
        date: 
          type: integer
        link:
          type: string
    CompleteArtwork:
      oneOf:
        - $ref: '#/components/schemas/MusicArtwork'
    MusicArtwork:
      allOf:
      - $ref: '#/components/schemas/BasicArtwork'
      - properties:
          category: 
            type: string
            enum:
             - music
          album:
            type: string
          description:
            type: string
          singer:
            type: string
          composer:
            type: string
          author:
            type: string
        
paths:
  /artworks:
    get:
      description: "search for artworks"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                   $ref: "#/components/schemas/CompleteArtwork"
      parameters:
        - name: category
          in: query
          description: "category of the artwork"
          schema:
            $ref: "#/components/schemas/Category"
        - name: name
          in: query
          description: "name of the artwork"
          schema:
            type: string
        - name: date
          in: query
          description: "date of creation for the artwork"
          schema:
            type: string
            format: date
        - name: artist
          in: query
          description: "who created the artwork"
          schema:
            type: string
        - name: rawQuery
          in: query
          description: "direct seach for those terms"
          schema:
            type: string
  /artworks/{artworkId}:
    get:
      tags: 
      - "artwork"
      summary: "get artwork by Id"
      operationId: "getArworkById"
      parameters:
      - name: "artworkId"
        in: "path"
        description: "ID of artwork to return"
        required: true 
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CompleteArtwork"

externalDocs:
  description: "template for everything here"
  url: "https://editor.swagger.io/"